### ISSUE TITLE
[Question] Some questions about the operator

### ISSUE THREAD

**Issue by KONY128** [tass-io/tass-operator#12]
Plz I need help. QAQ

**Q1**

The function resource needs ``spec.resource`` field. But this isn't illustrated in ``config/crd/bases/serverless.tass.io_functions.yaml``. And it's not exist in ``config/crd/samples/serverless_v1alpha1_function.yaml``, too.

**Q2**

Function controller will always enter the finalizer execution logic. Is this correct?

I mean, whether ``instance.ObjectMeta.DeletionTimestamp.IsZero()`` is failed or not, ``reconcile()`` will add a function finalizer or execute the deletion process based on the finalizer name, why?

**Q3**

There's a validation for function ``spec.resource.cpu`` field, and it must be a string rather than int. Is this correct?

The configuration yaml of ``cpu: 1`` is wrong and ``cpu: "1"`` is correct. lol.

Furthermore, the type of ``memory`` is string, how should I input?

``1mb``, ``1M``, ``1024B``, ``1024Mb``, ``1 mb``, ``1 M``, ``1024 B``... 

Please give me a example. SOS. 

**Q4**

At now, when the operator contains no function, applying ``workflow`` will also start ``workflowruntime``, ``deployment``, ``service``, ``replicaset`` and ``pod``. And then when I apply ``function``, the operator told me the ``pod`` is already started.

Is this correct? I think a new applied function will not start any pod. lol.

**Comment by tx19980520** [comment]
Q3： `cpu: 1` is wrong and cpu: "1" is correct because of CRD type define. And local scheduler also needs memory format.

**Comment by linxuyalun** [comment]
> Q3： `cpu: 1` is wrong and cpu: "1" is correct because of CRD type define. And local scheduler also needs memory format.

I will use resource type in k8s, update this today

**Comment by linxuyalun** [comment]
Q1: you don't need to care about anything in the config dir, see types definition in `api/v1alpha1/workflow_types.go` or our doc

Q2: I don't understand this question

Q4: I didn't update the function for a long time, maybe there are some code samples that I didn't remove. However, this question is not clear to me. Did it throw an error? Or it just printed a log and the reconciliation progress was successful? If it was the latter one, it's ok

**Comment by linxuyalun** [comment]
Q4: I read the code and I find that I do create a Pod in function reconcile which is used to test before

I didn't delete it later, my fault. I will remove useless logic later

**Comment by linxuyalun** [comment]
Now the cpu & memory types are same as [`Quantity`](https://pkg.go.dev/k8s.io/apimachinery@v0.17.2/pkg/api/resource#Quantity), an [example](https://kubernetes.io/zh/docs/tasks/configure-pod-container/assign-cpu-resource/)

@tx19980520 @KONY128

**Comment by linxuyalun** [comment]
> Q4: I read the code and I find that I do create a Pod in function reconcile which is used to test before
> 
> I didn't delete it later, my fault. I will remove useless logic later

- [x] Remove useless function reconcile logic

**Comment by KONY128** [comment]
Thanks, guys.

It really helps.

I'll continue my work tonight.

**Comment by KONY128** [comment]
> Q1: you don't need to care about anything in the config dir, see types definition in `api/v1alpha1/workflow_types.go` or our doc
> 
> Q2: I don't understand this question
> 
> Q4: I didn't update the function for a long time, maybe there are some code samples that I didn't remove. However, this question is not clear to me. Did it throw an error? Or it just printed a log and the reconciliation progress was successful? If it was the latter one, it's ok

The question 2 means the ``reconcile()`` logic will always check ``instance.ObjectMeta.DeletionTimestamp.IsZero()`` field at first. And then do some corresponding logic about finalizers. What if I do not want to delete it? 

Well. I just wonder whether this fragment of code could run correctly, because as a matter of fact it's not so understandable for me.
