### ISSUE TITLE
[Question] Problems encountered in the handover of project code work

### ISSUE THREAD

**Issue by KONY128** [tass-io/tass-operator#2]
I have some naive questions about this operator:

1. I need to know where is the entrance of the call in ``Tass-cli``, and how does they connected to each other (is this connection handled by Kubernetes control plane and are all the requests handled in ``reconcile``?)
2. I need a simple introduction about the  functionality of project files (I do not know which file is important and which file is automatically generated that I need not to pay attention to)
3. Which part of this project is most needed to test? I think the tests may need to across ``Tass-cli`` and ``Tass-operator``
4. I need the developing progress of this project

**Comment by linxuyalun** [comment]
1. Entrance is the [`main.go`](https://github.com/tass-io/cli/blob/main/main.go). What's the meaning of "they", cli communicate with Operator by RESTful request.
2. For 2 & 3, I suggest that you read the document of [Operator Testing](https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html). I only have a quick view of it, so I cannot give you details. As far as I remembered, you need to write codes about the fake client which the library has already provided. As for the parts which you need to focus to test, well , I think you should   first be familiar with the testing parts, know the overall process.  [`groupversion_info.go`](https://github.com/tass-io/tass-operator/blob/main/api/v1alpha1/groupversion_info.go), [`zz_generated.deepcopy.go`](https://github.com/tass-io/tass-operator/blob/main/api/v1alpha1/zz_generated.deepcopy.go) and [`config`](https://github.com/tass-io/tass-operator/tree/main/config) are generated automatically.
3. See 2
4. What does "progress" mean? More explanation?
